# For licensing see accompanying LICENSE file.
# Copyright (C) 2025 Apple Inc. All Rights Reserved.

defaults:
  - base_t2i
  - _self_

model_name: black-forest-labs/FLUX.1-schnell  # Required

# Task configuration
task_name: white_bg_position_objects  # Base task name
initial_states:
  initial_states_str: empty #mistralai/Mistral-7B-Instruct-v0.1  # Options: a language model or a tag that's in initial_states_factory

input_space:
  obj: "cat" # you can also change it to "ball" or any other class.

output_map:
  output_map_str: object_position
  modality: image
  question: ${input_space.obj}

problem_type: discrete  # Options: "quantized", "discrete", "continuous"
time_steps: 1  # Required, time horizon T
